image: node:14-alpine

deploy:
  only:
    - release
  before_script:
    - apk add python3 make g++
  script:
    - npm install
    - npm run generate
    - mkdir public
    - mv dist/* public
  artifacts:
    paths:
      - public
