image: node:lts-alpine

build:
  stage: build
  only:
    - release
  before_script:
    - apk add python make g++
  script:
    - npm install
    - npm run generate
  after_script:
    - mkdir public
    - move dist/* public
  artifacts:
    paths:
      - public
